# font
font_family JetBrainsMono Nerd Font Mono
bold_font auto
italic_font auto
bold_italic_font auto
font_size 15
adjust_line_height 120%
adjust_column_width 0
force_ltr no

# cursor
cursor_shape block

# theme
background_opacity 0.95
url_style curly
initial_window_size no
initial_window_width 640
initial_window_height 480
window_padding_width 14
scrollbar_handle_opacity 0
scrollbar_track_opacity 0
scrollbar_track_hover_opacity 0
sync_to_monitor no

# key maps
map ctrl+return toggle_fullscreen

# apps
editor neovim
shell fish

# Map the emoji unicode ranges to Noto Color Emoji
symbol_map U+231A-U+231B,U+23E9-U+23EC,U+23F0,U+23F3,U+25FD-U+25FE,U+2614-U+2615,U+2648-U+2653,U+267F,U+2693,U+26A1,U+26AA-U+26AB,U+26BD-U+26BE,U+26C4-U+26C5,U+26CE,U+26D4,U+26EA,U+26F2-U+26F3,U+26F5,U+26FA,U+26FD,U+2702,U+2705,U+2708-U+270C,U+274C,U+274E,U+2753-U+2755,U+2757,U+2795-U+2797,U+27B0,U+27BF,U+2934-U+2935,U+2B05-U+2B07,U+2B1B-U+2B1C,U+2B50,U+2B55,U+3030,U+303D,U+3297,U+3299,U+1F000-U+1F9FF Noto Color Emoji


# BEGIN_KITTY_THEME
# Tokyo Night
include current-theme.conf
# END_KITTY_THEME
